spring.datasource.url: jdbc:postgresql://192.168.56.1:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.datasource.platform: postgres
spring.datasource.tomcat.driver-class-name: com.oracle.jdbc.OracleDriver

spring.datasource.initialization-mode: always